wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: tensorflow
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1630402525
    t:
      1:
      - 3
      4: 3.7.11
      5: 0.12.1
      8:
      - 1
      - 5
